/**
 * Comprehensive list of Israeli service provider sender domains.
 * Used to catch billing emails from Israeli companies even when the subject
 * doesn't contain standard subscription keywords.
 *
 * Checked against the email `from` header (sender address / display name).
 */

export const ISRAELI_SENDER_DOMAINS: string[] = [
  // ── Telecom & Internet ────────────────────────────────────────────────────
  "cellcom.co.il",
  "pelephone.co.il",
  "partner.co.il",
  "hot.net.il",
  "hot-mobile.co.il",
  "hotmobile.co.il",
  "bezeq.co.il",
  "bezeqint.net",
  "012.net.il",
  "013.net.il",
  "018.net.il",
  "019mobile.co.il",
  "019.net.il",
  "golan-telecom.co.il",
  "golantelecom.co.il",
  "xfone.co.il",
  "sting.co.il",
  "rami-levy.co.il", // Rami Levy telecom
  "ravtel.co.il",
  "netsmart.co.il",
  "coolnet.co.il",

  // ── Electricity, Water & Gas ──────────────────────────────────────────────
  "iec.co.il",
  "electric.co.il",
  "hagihon.co.il",
  "mekorot.co.il",
  "miyam.co.il",
  "gihon.co.il",
  "gihon-jerusalem.co.il",
  "tashtit.org.il",
  "paz.co.il",
  "paz-gas.co.il",
  "delek.co.il",
  "delek-energy.co.il",
  "sonol.co.il",
  "doralon.co.il",
  "dor-alon.co.il",
  "yellow.co.il",
  "ten.co.il",
  "super-gas.co.il",
  "supergas.co.il",
  "amisragas.co.il",
  "gas-ktzin.co.il",
  "meithal.co.il",

  // ── Banks ─────────────────────────────────────────────────────────────────
  "leumi.co.il",
  "bankleumi.co.il",
  "hapoalim.co.il",
  "discount.co.il",
  "discountbank.co.il",
  "mizrahi-tefahot.co.il",
  "mizrahitefahot.co.il",
  "fibi.co.il",
  "beinleumi.co.il",
  "benleumi.co.il",
  "otzar.co.il",
  "mercantile.co.il",
  "massad.co.il",
  "postal-bank.co.il",
  "bankhapoalim.co.il",
  "ibi.co.il",
  "bld.co.il",

  // ── Credit Cards & Payments ───────────────────────────────────────────────
  "cal.co.il",
  "cal-online.co.il",
  "isracard.co.il",
  "max.co.il",
  "max-finance.co.il",
  "visa.co.il",
  "americanexpress.co.il",
  "amex.co.il",
  "leumipay.co.il",
  "paybox.co.il",
  "bit.co.il",
  "pepper.co.il",
  "payoneer.com",

  // ── Insurance ─────────────────────────────────────────────────────────────
  "migdal.co.il",
  "harel.co.il",
  "clal.co.il",
  "clalbit.co.il",
  "phoenix.co.il",
  "thephoenix.co.il",
  "menora.co.il",
  "menoramivtachim.co.il",
  "ayalon.co.il",
  "shirbit.co.il",
  "shomera.co.il",
  "shlomo.co.il",
  "karnit.co.il",
  "bituahleumi.org.il",
  "btl.gov.il",
  "mivtachim.co.il",
  "amitim.co.il",
  "yelin.co.il",
  "ds.co.il",
  "meitavdash.co.il",
  "turbobit.co.il",
  "ariel-insurance.co.il",
  "penimi.co.il",
  "aiag.co.il",

  // ── Pension, Provident & Investment ──────────────────────────────────────
  "meitav.co.il",
  "meitav-dash.co.il",
  "altshuler.co.il",
  "alshaham.co.il",
  "psagot.co.il",
  "more.co.il",
  "excellence.co.il",
  "analyst.co.il",
  "leader.co.il",
  "keshet.co.il",
  "gmul.co.il",
  "moria.co.il",
  "mi-pension.co.il",
  "ness.co.il",
  "nesstech.co.il",
  "maman.co.il",
  "clalfinance.co.il",
  "harelfinance.co.il",
  "phoenix-investments.co.il",
  "ementor.co.il",

  // ── Healthcare ────────────────────────────────────────────────────────────
  "clalit.co.il",
  "maccabi.co.il",
  "maccabitech.com",
  "meuhedet.co.il",
  "leumit.co.il",
  "clalit-health.co.il",
  "maacabicare.co.il",

  // ── Government & Municipal ────────────────────────────────────────────────
  "gov.il",
  "mas.gov.il",
  "misim.gov.il",
  "npa.gov.il",
  "shaam.gov.il",
  "btl.gov.il",
  "justice.gov.il",
  "cbs.gov.il",
  "mof.gov.il",
  "economy.gov.il",
  "tel-aviv.gov.il",
  "tel-aviv-yafo.gov.il",
  "jerusalem.muni.il",
  "haifa.muni.il",
  "petah-tikva.muni.il",
  "ramat-gan.muni.il",
  "beerotayim.muni.il",
  "rishon.muni.il",
  "rishonlezion.muni.il",
  "kfar-saba.muni.il",
  "rehovot.muni.il",
  "holon.muni.il",
  "bat-yam.muni.il",
  "hod-hasharon.muni.il",
  "netanya.muni.il",
  "ashdod.muni.il",
  "beer-sheva.muni.il",
  "beersheva.muni.il",
  "nazareth.muni.il",

  // ── Transportation ────────────────────────────────────────────────────────
  "egged.co.il",
  "dan.co.il",
  "kavim.co.il",
  "nta.co.il",
  "rail.co.il",
  "israelrailways.co.il",
  "gotoglobal.com",
  "goto.co.il",
  "gett.com",
  "gettaxi.com",
  "moovit.com",
  "pango.co.il",
  "pangopark.co.il",
  "ravalit.co.il",
  "ayalonkvish.co.il",
  "kvish6.com",
  "transisraeli.co.il",
  "nesher.co.il",
  "afikim.co.il",
  "superbus.co.il",
  "nateevexpress.co.il",
  "metropoline.com",
  "elal.co.il",
  "issta.co.il",
  "gotoair.co.il",
  "arkia.co.il",

  // ── Parking & Tolls ───────────────────────────────────────────────────────
  "caspit.co.il",
  "parkway.co.il",
  "i-park.co.il",
  "ipark.co.il",
  "q-park.co.il",
  "atraf.co.il",

  // ── Supermarkets & Grocery ───────────────────────────────────────────────
  "shufersal.co.il",
  "shufersalonline.co.il",
  "rami-levy.co.il",
  "mega.co.il",
  "tivtaam.co.il",
  "tiv-taam.co.il",
  "yochananof.co.il",
  "victory.co.il",
  "osher-ad.co.il",
  "osheradmarket.co.il",
  "mahsanei-hashuk.co.il",
  "hazi-hinam.co.il",

  // ── Pharmacy & Health Retail ──────────────────────────────────────────────
  "super-pharm.co.il",
  "superpharm.co.il",
  "new-pharm.co.il",
  "newpharm.co.il",
  "be-pharmacy.co.il",
  "goodpharm.co.il",
  "pharmarket.co.il",

  // ── Fashion & Retail ─────────────────────────────────────────────────────
  "fox.co.il",
  "fox-group.com",
  "terminal-x.com",
  "terminalx.com",
  "golf-fashion.co.il",
  "golf-kids.co.il",
  "golfgroup.co.il",
  "castro.co.il",
  "renuar.co.il",
  "shilav.co.il",
  "maskit.co.il",
  "honigman.co.il",
  "sasson.co.il",
  "kenvelo.co.il",
  "twentyfourseven.co.il",
  "twentyfour.co.il",
  "connect.co.il",
  "connectfashion.co.il",
  "newbalance.co.il",
  "adidas.co.il",
  "nike.co.il",
  "laline.co.il",
  "intimissimi.co.il",

  // ── Electronics & Tech Retail ─────────────────────────────────────────────
  "ksp.co.il",
  "bug.co.il",
  "ivory.co.il",
  "mister-zol.co.il",
  "misterzol.co.il",
  "best-buy.co.il",
  "bestbuy.co.il",
  "zap.co.il",
  "icq.co.il",
  "idigital.co.il",
  "apple.com",
  "amazon.co.il",
  "microsoft.com",

  // ── Food Delivery & Restaurants ──────────────────────────────────────────
  "wolt.com",
  "10bis.co.il",
  "mishloha.co.il",
  "paidelivery.co.il",

  // ── Media & Entertainment ─────────────────────────────────────────────────
  "yes.co.il",
  "hot.co.il",
  "reshet.tv",
  "keshet12.com",
  "keshetmedia.co.il",
  "kan.org.il",
  "ort.org.il",
  "kan.co.il",
  "mako.co.il",
  "ynet.co.il",
  "haaretz.co.il",
  "themarker.com",
  "jpost.com",
  "globes.co.il",
  "calcalist.co.il",
  "walla.co.il",
  "sport5.co.il",
  "one.co.il",
  "cellnet.co.il",

  // ── Streaming ─────────────────────────────────────────────────────────────
  "netflix.com",
  "spotify.com",
  "google.com",
  "youtube.com",
  "amazon.com",
  "disney.co.il",
  "disneyplus.com",
  "apple.com",
  "dropbox.com",
  "zoom.us",
  "slack.com",
  "microsoft.com",
  "office.com",
  "adobe.com",
  "canva.com",
  "notion.so",
  "chatgpt.com",
  "openai.com",
  "anthropic.com",
  "github.com",
  "atlassian.com",
  "figma.com",
  "hubspot.com",
  "salesforce.com",

  // ── Real Estate & Home ────────────────────────────────────────────────────
  "yad2.co.il",
  "madlan.co.il",
  "homeless.co.il",
  "winwin.co.il",
  "nadlannet.co.il",
  "diranet.co.il",
  "komo.co.il",

  // ── Israeli SaaS & Startups ───────────────────────────────────────────────
  "monday.com",
  "wix.com",
  "fiverr.com",
  "lightricks.com",
  "gett.com",
  "moovit.com",
  "lemonade.com",
  "melio.co",
  "payoneer.com",
  "waves.net",
  "ironscales.com",
  "gloat.com",
  "similarweb.com",
  "radcom.com",
  "comodo.co.il",
  "cellebrite.com",

  // ── Education ─────────────────────────────────────────────────────────────
  "huji.ac.il",
  "tau.ac.il",
  "technion.ac.il",
  "bgu.ac.il",
  "weizmann.ac.il",
  "biu.ac.il",
  "openu.ac.il",
  "runi.ac.il",
  "idc.ac.il",
  "hac.ac.il",
  "mta.ac.il",
  "ariel.ac.il",
  "hit.ac.il",
  "afeka.ac.il",
  "ruppin.ac.il",

  // ── Home Services & Misc ─────────────────────────────────────────────────
  "israpost.co.il",
  "israelpost.co.il",
  "post.co.il",
  "dhl.co.il",
  "fedex.co.il",
  "ups.co.il",
  "sela.co.il",
  "leaan.co.il",
  "fattal.co.il",
  "isrotel.co.il",
  "danhotels.co.il",
  "atlas.co.il",
  "atlas-hotels.co.il",
  "prima.co.il",
  "prima-hotels.co.il",
  "booking.com",
  "airbnb.com",
  "gympass.com",
  "bsmart.co.il",
  "homesmart.co.il",
  "mycheck.io",
  "invoice4u.co.il",
  "cardcom.co.il",
  "rivhit.co.il",
  "icount.co.il",
  "hashavshevet.co.il",
  "priority.co.il",
];
